module.exports = {
  host: 'play.dogeland.vn',
  port: 25565,
  version: '1.21.1',
  username: 'MTBOTSHARD2',
  password: '',
  authMode: 'auto',
  modeHotbarSlot: 1,
  modeItemName: 'compass',
  modeSlot: 20,
  afkCommand: '/afk',
  afkRoomSlot: 0,
  checkCommand: '/shard balance',
  shardRegex: /(\d[\d,.]*)\s*shard/i,
  recipient: 'petertukogay',
  runDurationMinutes: 330,
  checkIntervalMinutes: 1,
  giftCooldownMinutes: 1,
  retryDelayMs: 10000,
  reconnectBaseMs: 20000,
  debugChat: true,
  antiAfk: false
};
