name: Dogeland Shard Bot
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main
concurrency:
  group: dogeland-bot
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    env:
      DOGELAND_PASSWORD: ${{ secrets.DOGELAND_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: node bot.js
